extends: spectral:oas

rules:
  oas3-server-not-example.com: true
  contact-properties: true
  tag-description: true

  oas3-unused-component: true
  oas3-parameter-description: true
  openapi-tags-alphabetical: true
