extends: spectral:oas

rules:
  oas3-parameter-description: true
  oas3-server-not-example.com: true
  openapi-tags-alphabetical: true
  contact-properties: true
  tag-description: true

  # disable some unhelpful lint rules temporarily
  oas3-unused-component: false
  oas3-parameter-description: false
  openapi-tags-alphabetical: false
