components:
  headers: {}
  parameters: {}
  responses: {}
  schemas: {}
externalDocs:
  description: Learn more about the Slack Web API
  url: https://api.slack.com/web
info:
  contact:
    name: Slack developer relations
    url: https://api.slack.com/support
  description: One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
  title: Slack Web API
  version: 1.5.0
openapi: 3.0.0
paths: {}
servers:
- description: Public slack API
  url: https://slack.com/api
