openapi: 3.0.0
info:
  contact:
    name: Slack developer relations
    url: https://api.slack.com/support
  description: One way to interact with the Slack platform is its HTTP RPC-based Web API, a
    collection of methods requiring OAuth 2.0-based user, bot, or workspace
    tokens blessed with related OAuth scopes.
  title: Slack Web API
  version: 1.5.0
tags: []
servers:
  - url: https://slack.com/api
paths:
  /admin.apps.approve:
    post:
      description: Approve an app for installation on a workspace.
      operationId: admin_apps_approve
      security:
        - slackAuth:
            - admin.apps:write
      tags:
        - admin.apps
        - admin
  /admin.apps.approved.list:
    get:
      description: List approved apps for an org or workspace.
      operationId: admin_apps_approved_list
      security:
        - slackAuth:
            - admin.apps:read
      tags:
        - admin.apps.approved
        - admin
  /admin.apps.requests.list:
    get:
      description: List app requests for a team/workspace.
      operationId: admin_apps_requests_list
      security:
        - slackAuth:
            - admin.apps:read
      tags:
        - admin.apps.requests
        - admin
  /admin.apps.restrict:
    post:
      description: Restrict an app for installation on a workspace.
      operationId: admin_apps_restrict
      security:
        - slackAuth:
            - admin.apps:write
      tags:
        - admin.apps
        - admin
  /admin.apps.restricted.list:
    get:
      description: List restricted apps for an org or workspace.
      operationId: admin_apps_restricted_list
      security:
        - slackAuth:
            - admin.apps:read
      tags:
        - admin.apps.restricted
        - admin
  /admin.conversations.setTeams:
    post:
      description: Set the workspaces in an Enterprise grid org that connect to a channel.
      operationId: admin_conversations_setTeams
      security:
        - slackAuth:
            - admin.conversations:write
      tags:
        - admin.conversations
        - admin
  /admin.emoji.add:
    post:
      description: Add an emoji.
      operationId: admin_emoji_add
      security:
        - slackAuth:
            - admin.teams:write
      tags:
        - admin.emoji
        - admin
  /admin.emoji.addAlias:
    post:
      description: Add an emoji alias.
      operationId: admin_emoji_addAlias
      security:
        - slackAuth:
            - admin.teams:write
      tags:
        - admin.emoji
        - admin
  /admin.emoji.list:
    get:
      description: List emoji for an Enterprise Grid organization.
      operationId: admin_emoji_list
      security:
        - slackAuth:
            - admin.teams:read
      tags:
        - admin.emoji
        - admin
  /admin.emoji.remove:
    post:
      description: Remove an emoji across an Enterprise Grid organization
      operationId: admin_emoji_remove
      security:
        - slackAuth:
            - admin.teams:write
      tags:
        - admin.emoji
        - admin
  /admin.emoji.rename:
    post:
      description: Rename an emoji.
      operationId: admin_emoji_rename
      security:
        - slackAuth:
            - admin.teams:write
      tags:
        - admin.emoji
        - admin
  /admin.inviteRequests.approve:
    post:
      description: Approve a workspace invite request.
      operationId: admin_inviteRequests_approve
      security:
        - slackAuth:
            - admin.invites:write
      tags:
        - admin.inviteRequests
        - admin
  /admin.inviteRequests.approved.list:
    get:
      description: List all approved workspace invite requests.
      operationId: admin_inviteRequests_approved_list
      security:
        - slackAuth:
            - admin.invites:read
      tags:
        - admin.inviteRequests.approved
        - admin
  /admin.inviteRequests.denied.list:
    get:
      description: List all denied workspace invite requests.
      operationId: admin_inviteRequests_denied_list
      security:
        - slackAuth:
            - admin.invites:read
      tags:
        - admin.inviteRequests.denied
        - admin
  /admin.inviteRequests.deny:
    post:
      description: Deny a workspace invite request.
      operationId: admin_inviteRequests_deny
      security:
        - slackAuth:
            - admin.invites:write
      tags:
        - admin.inviteRequests
        - admin
  /admin.inviteRequests.list:
    get:
      description: List all pending workspace invite requests.
      operationId: admin_inviteRequests_list
      security:
        - slackAuth:
            - admin.invites:read
      tags:
        - admin.inviteRequests
        - admin
  /admin.teams.admins.list:
    get:
      description: List all of the admins on a given workspace.
      operationId: admin_teams_admins_list
      security:
        - slackAuth:
            - admin.teams:read
      tags:
        - admin.teams.admins
        - admin
  /admin.teams.create:
    post:
      description: Create an Enterprise team.
      operationId: admin_teams_create
      security:
        - slackAuth:
            - admin.teams:write
      tags:
        - admin.teams
        - admin
  /admin.teams.list:
    get:
      description: List all teams on an Enterprise organization
      operationId: admin_teams_list
      security:
        - slackAuth:
            - admin.teams:read
      tags:
        - admin.teams
        - admin
  /admin.teams.owners.list:
    get:
      description: List all of the owners on a given workspace.
      operationId: admin_teams_owners_list
      security:
        - slackAuth:
            - admin.teams:read
      tags:
        - admin.teams.owners
        - admin
  /admin.teams.settings.info:
    get:
      description: Fetch information about settings in a workspace
      operationId: admin_teams_settings_info
      security:
        - slackAuth:
            - admin.teams:read
      tags:
        - admin.teams.settings
        - admin
  /admin.teams.settings.setDefaultChannels:
    post:
      description: Set the default channels of a workspace.
      operationId: admin_teams_settings_setDefaultChannels
      security:
        - slackAuth:
            - admin.teams:write
      tags:
        - admin.teams.settings
        - admin
  /admin.teams.settings.setDescription:
    post:
      description: Set the description of a given workspace.
      operationId: admin_teams_settings_setDescription
      security:
        - slackAuth:
            - admin.teams:write
      tags:
        - admin.teams.settings
        - admin
  /admin.teams.settings.setDiscoverability:
    post:
      description: An API method that allows admins to set the discoverability of a given
        workspace
      operationId: admin_teams_settings_setDiscoverability
      security:
        - slackAuth:
            - admin.teams:write
      tags:
        - admin.teams.settings
        - admin
  /admin.teams.settings.setIcon:
    post:
      description: Sets the icon of a workspace.
      operationId: admin_teams_settings_setIcon
      security:
        - slackAuth:
            - admin.teams:write
      tags:
        - admin.teams.settings
        - admin
  /admin.teams.settings.setName:
    post:
      description: Set the name of a given workspace.
      operationId: admin_teams_settings_setName
      security:
        - slackAuth:
            - admin.teams:write
      tags:
        - admin.teams.settings
        - admin
  /admin.users.assign:
    post:
      description: Add an Enterprise user to a workspace.
      operationId: admin_users_assign
      security:
        - slackAuth:
            - admin.users:write
      tags:
        - admin.users
        - admin
  /admin.users.invite:
    post:
      description: Invite a user to a workspace.
      operationId: admin_users_invite
      security:
        - slackAuth:
            - admin.users:write
      tags:
        - admin.users
        - admin
  /admin.users.list:
    get:
      description: List users on a workspace
      operationId: admin_users_list
      security:
        - slackAuth:
            - admin.users:read
      tags:
        - admin.users
        - admin
  /admin.users.remove:
    post:
      description: Remove a user from a workspace.
      operationId: admin_users_remove
      security:
        - slackAuth:
            - admin.users:write
      tags:
        - admin.users
        - admin
  /admin.users.session.reset:
    post:
      description: Wipes all valid sessions on all devices for a given user
      operationId: admin_users_session_reset
      security:
        - slackAuth:
            - admin.users:write
      tags:
        - admin.users.session
        - admin
  /admin.users.setAdmin:
    post:
      description: Set an existing guest, regular user, or owner to be an admin user.
      operationId: admin_users_setAdmin
      security:
        - slackAuth:
            - admin.users:write
      tags:
        - admin.users
        - admin
  /admin.users.setExpiration:
    post:
      description: Set an expiration for a guest user
      operationId: admin_users_setExpiration
      security:
        - slackAuth:
            - admin.users:write
      tags:
        - admin.users
        - admin
  /admin.users.setOwner:
    post:
      description: Set an existing guest, regular user, or admin user to be a workspace
        owner.
      operationId: admin_users_setOwner
      security:
        - slackAuth:
            - admin.users:write
      tags:
        - admin.users
        - admin
  /admin.users.setRegular:
    post:
      description: Set an existing guest user, admin user, or owner to be a regular user.
      operationId: admin_users_setRegular
      security:
        - slackAuth:
            - admin.users:write
      tags:
        - admin.users
        - admin
  /api.test:
    get:
      description: Checks API calling code.
      operationId: api_test
      security:
        - slackAuth:
            - none
      tags:
        - api
  /apps.permissions.info:
    get:
      description: Returns list of permissions this app has on a team.
      operationId: apps_permissions_info
      security:
        - slackAuth:
            - none
      tags:
        - apps.permissions
        - apps
  /apps.permissions.request:
    get:
      description: Allows an app to request additional scopes
      operationId: apps_permissions_request
      security:
        - slackAuth:
            - none
      tags:
        - apps.permissions
        - apps
  /apps.permissions.resources.list:
    get:
      description: Returns list of resource grants this app has on a team.
      operationId: apps_permissions_resources_list
      security:
        - slackAuth:
            - none
      tags:
        - apps.permissions.resources
        - apps
  /apps.permissions.scopes.list:
    get:
      description: Returns list of scopes this app has on a team.
      operationId: apps_permissions_scopes_list
      security:
        - slackAuth:
            - none
      tags:
        - apps.permissions.scopes
        - apps
  /apps.permissions.users.list:
    get:
      description: Returns list of user grants and corresponding scopes this app has on a
        team.
      operationId: apps_permissions_users_list
      security:
        - slackAuth:
            - none
      tags:
        - apps.permissions.users
        - apps
  /apps.permissions.users.request:
    get:
      description: Enables an app to trigger a permissions modal to grant an app access to
        a user access scope.
      operationId: apps_permissions_users_request
      security:
        - slackAuth:
            - none
      tags:
        - apps.permissions.users
        - apps
  /apps.uninstall:
    get:
      description: Uninstalls your app from a workspace.
      operationId: apps_uninstall
      security:
        - slackAuth:
            - none
      tags:
        - apps
  /auth.revoke:
    get:
      description: Revokes a token.
      operationId: auth_revoke
      security:
        - slackAuth:
            - none
      tags:
        - auth
  /auth.test:
    get:
      description: Checks authentication & identity.
      operationId: auth_test
      security:
        - slackAuth:
            - none
      tags:
        - auth
  /bots.info:
    get:
      description: Gets information about a bot user.
      operationId: bots_info
      security:
        - slackAuth:
            - users:read
      tags:
        - bots
  /channels.archive:
    post:
      description: Archives a channel.
      operationId: channels_archive
      security:
        - slackAuth:
            - channels:write
      tags:
        - channels
  /channels.create:
    post:
      description: Creates a channel.
      operationId: channels_create
      security:
        - slackAuth:
            - channels:write
      tags:
        - channels
  /channels.history:
    get:
      description: Fetches history of messages and events from a channel.
      operationId: channels_history
      security:
        - slackAuth:
            - channels:history
      tags:
        - channels
  /channels.info:
    get:
      description: Gets information about a channel.
      operationId: channels_info
      security:
        - slackAuth:
            - channels:read
      tags:
        - channels
  /channels.invite:
    post:
      description: Invites a user to a channel.
      operationId: channels_invite
      security:
        - slackAuth:
            - channels:write
      tags:
        - channels
  /channels.join:
    post:
      description: Joins a channel, creating it if needed.
      operationId: channels_join
      security:
        - slackAuth:
            - channels:write
      tags:
        - channels
  /channels.kick:
    post:
      description: Removes a user from a channel.
      operationId: channels_kick
      security:
        - slackAuth:
            - channels:write
      tags:
        - channels
  /channels.leave:
    post:
      description: Leaves a channel.
      operationId: channels_leave
      security:
        - slackAuth:
            - channels:write
      tags:
        - channels
  /channels.list:
    get:
      description: Lists all channels in a Slack team.
      operationId: channels_list
      security:
        - slackAuth:
            - channels:read
      tags:
        - channels
  /channels.mark:
    post:
      description: Sets the read cursor in a channel.
      operationId: channels_mark
      security:
        - slackAuth:
            - channels:write
      tags:
        - channels
  /channels.rename:
    post:
      description: Renames a channel.
      operationId: channels_rename
      security:
        - slackAuth:
            - channels:write
      tags:
        - channels
  /channels.replies:
    get:
      description: Retrieve a thread of messages posted to a channel
      operationId: channels_replies
      security:
        - slackAuth:
            - channels:history
      tags:
        - channels
  /channels.setPurpose:
    post:
      description: Sets the purpose for a channel.
      operationId: channels_setPurpose
      security:
        - slackAuth:
            - channels:write
      tags:
        - channels
  /channels.setTopic:
    post:
      description: Sets the topic for a channel.
      operationId: channels_setTopic
      security:
        - slackAuth:
            - channels:write
      tags:
        - channels
  /channels.unarchive:
    post:
      description: Unarchives a channel.
      operationId: channels_unarchive
      security:
        - slackAuth:
            - channels:write
      tags:
        - channels
  /chat.delete:
    post:
      description: Deletes a message.
      operationId: chat_delete
      security:
        - slackAuth:
            - chat:write:user
            - chat:write:bot
      tags:
        - chat
  /chat.deleteScheduledMessage:
    post:
      description: Deletes a pending scheduled message from the queue.
      operationId: chat_deleteScheduledMessage
      security:
        - slackAuth:
            - chat:write:user
            - chat:write:bot
      tags:
        - chat
  /chat.getPermalink:
    get:
      description: Retrieve a permalink URL for a specific extant message
      operationId: chat_getPermalink
      security:
        - slackAuth:
            - none
      tags:
        - chat
  /chat.meMessage:
    post:
      description: Share a me message into a channel.
      operationId: chat_meMessage
      security:
        - slackAuth:
            - chat:write:user
      tags:
        - chat
  /chat.postEphemeral:
    post:
      description: Sends an ephemeral message to a user in a channel.
      operationId: chat_postEphemeral
      security:
        - slackAuth:
            - chat:write:user
            - chat:write:bot
      tags:
        - chat
  /chat.postMessage:
    post:
      description: Sends a message to a channel.
      operationId: chat_postMessage
      security:
        - slackAuth:
            - chat:write:user
            - chat:write:bot
      tags:
        - chat
  /chat.scheduleMessage:
    post:
      description: Schedules a message to be sent to a channel.
      operationId: chat_scheduleMessage
      security:
        - slackAuth:
            - chat:write:user
            - chat:write:bot
      tags:
        - chat
  /chat.scheduledMessages.list:
    get:
      description: Returns a list of scheduled messages.
      operationId: chat_scheduledMessages_list
      security:
        - slackAuth:
            - none
      tags:
        - chat.scheduledMessages
        - chat
  /chat.unfurl:
    post:
      description: Provide custom unfurl behavior for user-posted URLs
      operationId: chat_unfurl
      security:
        - slackAuth:
            - links:write
      tags:
        - chat
  /chat.update:
    post:
      description: Updates a message.
      operationId: chat_update
      security:
        - slackAuth:
            - chat:write:user
            - chat:write:bot
      tags:
        - chat
  /conversations.archive:
    post:
      description: Archives a conversation.
      operationId: conversations_archive
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      tags:
        - conversations
  /conversations.close:
    post:
      description: Closes a direct message or multi-person direct message.
      operationId: conversations_close
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      tags:
        - conversations
  /conversations.create:
    post:
      description: Initiates a public or private channel-based conversation
      operationId: conversations_create
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      tags:
        - conversations
  /conversations.history:
    get:
      description: Fetches a conversation's history of messages and events.
      operationId: conversations_history
      security:
        - slackAuth:
            - channels:history
            - groups:history
            - im:history
            - mpim:history
      tags:
        - conversations
  /conversations.info:
    get:
      description: Retrieve information about a conversation.
      operationId: conversations_info
      security:
        - slackAuth:
            - channels:read
            - groups:read
            - im:read
            - mpim:read
      tags:
        - conversations
  /conversations.invite:
    post:
      description: Invites users to a channel.
      operationId: conversations_invite
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      tags:
        - conversations
  /conversations.join:
    post:
      description: Joins an existing conversation.
      operationId: conversations_join
      security:
        - slackAuth:
            - channels:write
      tags:
        - conversations
  /conversations.kick:
    post:
      description: Removes a user from a conversation.
      operationId: conversations_kick
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      tags:
        - conversations
  /conversations.leave:
    post:
      description: Leaves a conversation.
      operationId: conversations_leave
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      tags:
        - conversations
  /conversations.list:
    get:
      description: Lists all channels in a Slack team.
      operationId: conversations_list
      security:
        - slackAuth:
            - channels:read
            - groups:read
            - im:read
            - mpim:read
      tags:
        - conversations
  /conversations.members:
    get:
      description: Retrieve members of a conversation.
      operationId: conversations_members
      security:
        - slackAuth:
            - channels:read
            - groups:read
            - im:read
            - mpim:read
      tags:
        - conversations
  /conversations.open:
    post:
      description: Opens or resumes a direct message or multi-person direct message.
      operationId: conversations_open
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      tags:
        - conversations
  /conversations.rename:
    post:
      description: Renames a conversation.
      operationId: conversations_rename
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      tags:
        - conversations
  /conversations.replies:
    get:
      description: Retrieve a thread of messages posted to a conversation
      operationId: conversations_replies
      security:
        - slackAuth:
            - channels:history
            - groups:history
            - im:history
            - mpim:history
      tags:
        - conversations
  /conversations.setPurpose:
    post:
      description: Sets the purpose for a conversation.
      operationId: conversations_setPurpose
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      tags:
        - conversations
  /conversations.setTopic:
    post:
      description: Sets the topic for a conversation.
      operationId: conversations_setTopic
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      tags:
        - conversations
  /conversations.unarchive:
    post:
      description: Reverses conversation archival.
      operationId: conversations_unarchive
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      tags:
        - conversations
  /dialog.open:
    get:
      description: Open a dialog with a user
      operationId: dialog_open
      security:
        - slackAuth:
            - none
      tags:
        - dialog
  /dnd.endDnd:
    post:
      description: Ends the current user's Do Not Disturb session immediately.
      operationId: dnd_endDnd
      security:
        - slackAuth:
            - dnd:write
      tags:
        - dnd
  /dnd.endSnooze:
    post:
      description: Ends the current user's snooze mode immediately.
      operationId: dnd_endSnooze
      security:
        - slackAuth:
            - dnd:write
      tags:
        - dnd
  /dnd.info:
    get:
      description: Retrieves a user's current Do Not Disturb status.
      operationId: dnd_info
      security:
        - slackAuth:
            - dnd:read
      tags:
        - dnd
  /dnd.setSnooze:
    post:
      description: Turns on Do Not Disturb mode for the current user, or changes its
        duration.
      operationId: dnd_setSnooze
      security:
        - slackAuth:
            - dnd:write
      tags:
        - dnd
  /dnd.teamInfo:
    get:
      description: Retrieves the Do Not Disturb status for up to 50 users on a team.
      operationId: dnd_teamInfo
      security:
        - slackAuth:
            - dnd:read
      tags:
        - dnd
  /emoji.list:
    get:
      description: Lists custom emoji for a team.
      operationId: emoji_list
      security:
        - slackAuth:
            - emoji:read
      tags:
        - emoji
  /files.comments.delete:
    post:
      description: Deletes an existing comment on a file.
      operationId: files_comments_delete
      security:
        - slackAuth:
            - files:write:user
      tags:
        - files.comments
        - files
  /files.delete:
    post:
      description: Deletes a file.
      operationId: files_delete
      security:
        - slackAuth:
            - files:write:user
      tags:
        - files
  /files.info:
    get:
      description: Gets information about a team file.
      operationId: files_info
      security:
        - slackAuth:
            - files:read
      tags:
        - files
  /files.list:
    get:
      description: Lists & filters team files.
      operationId: files_list
      security:
        - slackAuth:
            - files:read
      tags:
        - files
  /files.remote.add:
    post:
      description: Adds a file from a remote service
      operationId: files_remote_add
      security:
        - slackAuth:
            - remote_files:write
      tags:
        - files.remote
        - files
  /files.remote.info:
    get:
      description: Retrieve information about a remote file added to Slack
      operationId: files_remote_info
      security:
        - slackAuth:
            - remote_files:read
      tags:
        - files.remote
        - files
  /files.remote.list:
    get:
      description: Retrieve information about a remote file added to Slack
      operationId: files_remote_list
      security:
        - slackAuth:
            - remote_files:read
      tags:
        - files.remote
        - files
  /files.remote.remove:
    post:
      description: Remove a remote file.
      operationId: files_remote_remove
      security:
        - slackAuth:
            - remote_files:write
      tags:
        - files.remote
        - files
  /files.remote.share:
    get:
      description: Share a remote file into a channel.
      operationId: files_remote_share
      security:
        - slackAuth:
            - remote_files:share
      tags:
        - files.remote
        - files
  /files.remote.update:
    post:
      description: Updates an existing remote file.
      operationId: files_remote_update
      security:
        - slackAuth:
            - remote_files:write
      tags:
        - files.remote
        - files
  /files.revokePublicURL:
    post:
      description: Revokes public/external sharing access for a file
      operationId: files_revokePublicURL
      security:
        - slackAuth:
            - files:write:user
      tags:
        - files
  /files.sharedPublicURL:
    post:
      description: Enables a file for public/external sharing.
      operationId: files_sharedPublicURL
      security:
        - slackAuth:
            - files:write:user
      tags:
        - files
  /files.upload:
    post:
      description: Uploads or creates a file.
      operationId: files_upload
      security:
        - slackAuth:
            - files:write:user
      tags:
        - files
  /groups.archive:
    post:
      description: Archives a private channel.
      operationId: groups_archive
      security:
        - slackAuth:
            - groups:write
      tags:
        - groups
  /groups.create:
    post:
      description: Creates a private channel.
      operationId: groups_create
      security:
        - slackAuth:
            - groups:write
      tags:
        - groups
  /groups.createChild:
    post:
      description: Clones and archives a private channel.
      operationId: groups_createChild
      security:
        - slackAuth:
            - groups:write
      tags:
        - groups
  /groups.history:
    get:
      description: Fetches history of messages and events from a private channel.
      operationId: groups_history
      security:
        - slackAuth:
            - groups:history
      tags:
        - groups
  /groups.info:
    get:
      description: Gets information about a private channel.
      operationId: groups_info
      security:
        - slackAuth:
            - groups:read
      tags:
        - groups
  /groups.invite:
    post:
      description: Invites a user to a private channel.
      operationId: groups_invite
      security:
        - slackAuth:
            - groups:write
      tags:
        - groups
  /groups.kick:
    post:
      description: Removes a user from a private channel.
      operationId: groups_kick
      security:
        - slackAuth:
            - groups:write
      tags:
        - groups
  /groups.leave:
    post:
      description: Leaves a private channel.
      operationId: groups_leave
      security:
        - slackAuth:
            - groups:write
      tags:
        - groups
  /groups.list:
    get:
      description: Lists private channels that the calling user has access to.
      operationId: groups_list
      security:
        - slackAuth:
            - groups:read
      tags:
        - groups
  /groups.mark:
    post:
      description: Sets the read cursor in a private channel.
      operationId: groups_mark
      security:
        - slackAuth:
            - groups:write
      tags:
        - groups
  /groups.open:
    post:
      description: Opens a private channel.
      operationId: groups_open
      security:
        - slackAuth:
            - groups:write
      tags:
        - groups
  /groups.rename:
    post:
      description: Renames a private channel.
      operationId: groups_rename
      security:
        - slackAuth:
            - groups:write
      tags:
        - groups
  /groups.replies:
    get:
      description: Retrieve a thread of messages posted to a private channel
      operationId: groups_replies
      security:
        - slackAuth:
            - groups:history
      tags:
        - groups
  /groups.setPurpose:
    post:
      description: Sets the purpose for a private channel.
      operationId: groups_setPurpose
      security:
        - slackAuth:
            - groups:write
      tags:
        - groups
  /groups.setTopic:
    post:
      description: Sets the topic for a private channel.
      operationId: groups_setTopic
      security:
        - slackAuth:
            - groups:write
      tags:
        - groups
  /groups.unarchive:
    post:
      description: Unarchives a private channel.
      operationId: groups_unarchive
      security:
        - slackAuth:
            - groups:write
      tags:
        - groups
  /im.close:
    post:
      description: Close a direct message channel.
      operationId: im_close
      security:
        - slackAuth:
            - im:write
      tags:
        - im
  /im.history:
    get:
      description: Fetches history of messages and events from direct message channel.
      operationId: im_history
      security:
        - slackAuth:
            - im:history
      tags:
        - im
  /im.list:
    get:
      description: Lists direct message channels for the calling user.
      operationId: im_list
      security:
        - slackAuth:
            - im:read
      tags:
        - im
  /im.mark:
    post:
      description: Sets the read cursor in a direct message channel.
      operationId: im_mark
      security:
        - slackAuth:
            - im:write
      tags:
        - im
  /im.open:
    post:
      description: Opens a direct message channel.
      operationId: im_open
      security:
        - slackAuth:
            - im:write
      tags:
        - im
  /im.replies:
    get:
      description: Retrieve a thread of messages posted to a direct message conversation
      operationId: im_replies
      security:
        - slackAuth:
            - im:history
      tags:
        - im
  /migration.exchange:
    get:
      description: For Enterprise Grid workspaces, map local user IDs to global user IDs
      operationId: migration_exchange
      security:
        - slackAuth:
            - tokens.basic
      tags:
        - migration
  /mpim.close:
    post:
      description: Closes a multiparty direct message channel.
      operationId: mpim_close
      security:
        - slackAuth:
            - mpim:write
      tags:
        - mpim
  /mpim.history:
    get:
      description: Fetches history of messages and events from a multiparty direct message.
      operationId: mpim_history
      security:
        - slackAuth:
            - mpim:history
      tags:
        - mpim
  /mpim.list:
    get:
      description: Lists multiparty direct message channels for the calling user.
      operationId: mpim_list
      security:
        - slackAuth:
            - mpim:read
      tags:
        - mpim
  /mpim.mark:
    post:
      description: Sets the read cursor in a multiparty direct message channel.
      operationId: mpim_mark
      security:
        - slackAuth:
            - mpim:write
      tags:
        - mpim
  /mpim.open:
    post:
      description: This method opens a multiparty direct message.
      operationId: mpim_open
      security:
        - slackAuth:
            - mpim:write
      tags:
        - mpim
  /mpim.replies:
    get:
      description: Retrieve a thread of messages posted to a direct message conversation
        from a multiparty direct message.
      operationId: mpim_replies
      security:
        - slackAuth:
            - mpim:history
      tags:
        - mpim
  /oauth.access:
    get:
      description: Exchanges a temporary OAuth verifier code for an access token.
      operationId: oauth_access
      security:
        - slackAuth:
            - none
      tags:
        - oauth
  /oauth.token:
    get:
      description: Exchanges a temporary OAuth verifier code for a workspace token.
      operationId: oauth_token
      security:
        - slackAuth:
            - none
      tags:
        - oauth
  /oauth.v2.access:
    get:
      description: Exchanges a temporary OAuth verifier code for an access token.
      operationId: oauth_v2_access
      security:
        - slackAuth:
            - none
      tags:
        - oauth.v2
        - oauth
  /pins.add:
    post:
      description: Pins an item to a channel.
      operationId: pins_add
      security:
        - slackAuth:
            - pins:write
      tags:
        - pins
  /pins.list:
    get:
      description: Lists items pinned to a channel.
      operationId: pins_list
      security:
        - slackAuth:
            - pins:read
      tags:
        - pins
  /pins.remove:
    post:
      description: Un-pins an item from a channel.
      operationId: pins_remove
      security:
        - slackAuth:
            - pins:write
      tags:
        - pins
  /reactions.add:
    post:
      description: Adds a reaction to an item.
      operationId: reactions_add
      security:
        - slackAuth:
            - reactions:write
      tags:
        - reactions
  /reactions.get:
    get:
      description: Gets reactions for an item.
      operationId: reactions_get
      security:
        - slackAuth:
            - reactions:read
      tags:
        - reactions
  /reactions.list:
    get:
      description: Lists reactions made by a user.
      operationId: reactions_list
      security:
        - slackAuth:
            - reactions:read
      tags:
        - reactions
  /reactions.remove:
    post:
      description: Removes a reaction from an item.
      operationId: reactions_remove
      security:
        - slackAuth:
            - reactions:write
      tags:
        - reactions
  /reminders.add:
    post:
      description: Creates a reminder.
      operationId: reminders_add
      security:
        - slackAuth:
            - reminders:write
      tags:
        - reminders
  /reminders.complete:
    post:
      description: Marks a reminder as complete.
      operationId: reminders_complete
      security:
        - slackAuth:
            - reminders:write
      tags:
        - reminders
  /reminders.delete:
    post:
      description: Deletes a reminder.
      operationId: reminders_delete
      security:
        - slackAuth:
            - reminders:write
      tags:
        - reminders
  /reminders.info:
    get:
      description: Gets information about a reminder.
      operationId: reminders_info
      security:
        - slackAuth:
            - reminders:read
      tags:
        - reminders
  /reminders.list:
    get:
      description: Lists all reminders created by or for a given user.
      operationId: reminders_list
      security:
        - slackAuth:
            - reminders:read
      tags:
        - reminders
  /rtm.connect:
    get:
      description: Starts a Real Time Messaging session.
      operationId: rtm_connect
      security:
        - slackAuth:
            - rtm:stream
      tags:
        - rtm
  /search.messages:
    get:
      description: Searches for messages matching a query.
      operationId: search_messages
      security:
        - slackAuth:
            - search:read
      tags:
        - search
  /stars.add:
    post:
      description: Adds a star to an item.
      operationId: stars_add
      security:
        - slackAuth:
            - stars:write
      tags:
        - stars
  /stars.list:
    get:
      description: Lists stars for a user.
      operationId: stars_list
      security:
        - slackAuth:
            - stars:read
      tags:
        - stars
  /stars.remove:
    post:
      description: Removes a star from an item.
      operationId: stars_remove
      security:
        - slackAuth:
            - stars:write
      tags:
        - stars
  /team.accessLogs:
    get:
      description: Gets the access logs for the current team.
      operationId: team_accessLogs
      security:
        - slackAuth:
            - admin
      tags:
        - team
  /team.billableInfo:
    get:
      description: Gets billable users information for the current team.
      operationId: team_billableInfo
      security:
        - slackAuth:
            - admin
      tags:
        - team
  /team.info:
    get:
      description: Gets information about the current team.
      operationId: team_info
      security:
        - slackAuth:
            - team:read
      tags:
        - team
  /team.integrationLogs:
    get:
      description: Gets the integration logs for the current team.
      operationId: team_integrationLogs
      security:
        - slackAuth:
            - admin
      tags:
        - team
  /team.profile.get:
    get:
      description: Retrieve a team's profile.
      operationId: team_profile_get
      security:
        - slackAuth:
            - users.profile:read
      tags:
        - team.profile
        - team
  /usergroups.create:
    post:
      description: Create a User Group
      operationId: usergroups_create
      security:
        - slackAuth:
            - usergroups:write
      tags:
        - usergroups
  /usergroups.disable:
    post:
      description: Disable an existing User Group
      operationId: usergroups_disable
      security:
        - slackAuth:
            - usergroups:write
      tags:
        - usergroups
  /usergroups.enable:
    post:
      description: Enable a User Group
      operationId: usergroups_enable
      security:
        - slackAuth:
            - usergroups:write
      tags:
        - usergroups
  /usergroups.list:
    get:
      description: List all User Groups for a team
      operationId: usergroups_list
      security:
        - slackAuth:
            - usergroups:read
      tags:
        - usergroups
  /usergroups.update:
    post:
      description: Update an existing User Group
      operationId: usergroups_update
      security:
        - slackAuth:
            - usergroups:write
      tags:
        - usergroups
  /usergroups.users.list:
    get:
      description: List all users in a User Group
      operationId: usergroups_users_list
      security:
        - slackAuth:
            - usergroups:read
      tags:
        - usergroups.users
        - usergroups
  /usergroups.users.update:
    post:
      description: Update the list of users for a User Group
      operationId: usergroups_users_update
      security:
        - slackAuth:
            - usergroups:write
      tags:
        - usergroups.users
        - usergroups
  /users.conversations:
    get:
      description: List conversations the calling user may access.
      operationId: users_conversations
      security:
        - slackAuth:
            - channels:read
            - groups:read
            - im:read
            - mpim:read
      tags:
        - users
  /users.deletePhoto:
    post:
      description: Delete the user profile photo
      operationId: users_deletePhoto
      security:
        - slackAuth:
            - users.profile:write
      tags:
        - users
  /users.getPresence:
    get:
      description: Gets user presence information.
      operationId: users_getPresence
      security:
        - slackAuth:
            - users:read
      tags:
        - users
  /users.identity:
    get:
      description: Get a user's identity.
      operationId: users_identity
      security:
        - slackAuth:
            - identity.basic
      tags:
        - users
  /users.info:
    get:
      description: Gets information about a user.
      operationId: users_info
      security:
        - slackAuth:
            - users:read
      tags:
        - users
  /users.list:
    get:
      description: Lists all users in a Slack team.
      operationId: users_list
      security:
        - slackAuth:
            - users:read
      tags:
        - users
  /users.lookupByEmail:
    get:
      description: Find a user with an email address.
      operationId: users_lookupByEmail
      security:
        - slackAuth:
            - users:read.email
      tags:
        - users
  /users.profile.get:
    get:
      description: Retrieves a user's profile information.
      operationId: users_profile_get
      security:
        - slackAuth:
            - users.profile:read
      tags:
        - users.profile
        - users
  /users.profile.set:
    post:
      description: Set the profile information for a user.
      operationId: users_profile_set
      security:
        - slackAuth:
            - users.profile:write
      tags:
        - users.profile
        - users
  /users.setActive:
    post:
      description: Marked a user as active. Deprecated and non-functional.
      operationId: users_setActive
      security:
        - slackAuth:
            - users:write
      tags:
        - users
  /users.setPhoto:
    post:
      description: Set the user profile photo
      operationId: users_setPhoto
      security:
        - slackAuth:
            - users.profile:write
      tags:
        - users
  /users.setPresence:
    post:
      description: Manually sets user presence.
      operationId: users_setPresence
      security:
        - slackAuth:
            - users:write
      tags:
        - users
  /views.open:
    get:
      description: Open a view for a user.
      operationId: views_open
      security:
        - slackAuth:
            - none
      tags:
        - views
  /views.publish:
    get:
      description: Publish a static view for a User.
      operationId: views_publish
      security:
        - slackAuth:
            - none
      tags:
        - views
  /views.push:
    get:
      description: Push a view onto the stack of a root view.
      operationId: views_push
      security:
        - slackAuth:
            - none
      tags:
        - views
  /views.update:
    get:
      description: Update an existing view.
      operationId: views_update
      security:
        - slackAuth:
            - none
      tags:
        - views
components:
  securitySchemes:
    slackAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://slack.com/oauth/authorize
          tokenUrl: https://slack.com/api/oauth.access
          scopes:
            admin: admin
            admin.apps:read: admin.apps:read
            admin.apps:write: admin.apps:write
            admin.conversations:write: admin.conversations:write
            admin.invites:read: admin.invites:read
            admin.invites:write: admin.invites:write
            admin.teams:read: admin.teams:read
            admin.teams:write: admin.teams:write
            admin.users:read: admin.users:read
            admin.users:write: admin.users:write
            bot: Bot user scope
            channels:history: channels:history
            channels:read: channels:read
            channels:write: channels:write
            chat:write: chat:write
            chat:write:bot: Author messages as a bot
            chat:write:user: chat:write:user
            conversations:history: conversations:history
            conversations:read: conversations:read
            conversations:write: conversations:write
            dnd:read: dnd:read
            dnd:write: dnd:write
            emoji:read: emoji:read
            files:read: files:read
            files:write:user: files:write:user
            groups:history: groups:history
            groups:read: groups:read
            groups:write: groups:write
            identity.basic: identity.basic
            im:history: im:history
            im:read: im:read
            im:write: im:write
            links:write: links:write
            mpim:history: mpim:history
            mpim:read: mpim:read
            mpim:write: mpim:write
            none: No scope required
            pins:read: pins:read
            pins:write: pins:write
            reactions:read: reactions:read
            reactions:write: reactions:write
            reminders:read: reminders:read
            reminders:write: reminders:write
            remote_files:read: remote_files:read
            remote_files:share: remote_files:share
            remote_files:write: remote_files:write
            rtm:stream: rtm:stream
            search:read: search:read
            stars:read: stars:read
            stars:write: stars:write
            team:read: team:read
            tokens.basic: tokens.basic
            usergroups:read: usergroups:read
            usergroups:write: usergroups:write
            users.profile:read: users.profile:read
            users.profile:write: users.profile:write
            users:read: users:read
            users:read.email: users:read.email
            users:write: users:write