paths:
  /admin.teams.settings.setDefaultChannels:
    post:
      tags:
        - admin.teams.settings
        - admin
      description: Set the default channels of a workspace.
      externalDocs:
        description: API method documentation
        url: https://api.slack.com/methods/admin.teams.settings.setDefaultChannels
      operationId: admin_teams_settings_setDefaultChannels
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - channel_ids
                - team_id
                - token
              properties:
                token:
                  type: string
                  description: "Authentication token. Requires scope: `admin.teams:write`"
                team_id:
                  type: string
                  description: ID for the workspace to set the default channel for.
                channel_ids:
                  type: string
                  description: An array of channel IDs.
        required: true
      responses:
        "200":
          description: Typical success response
          content:
            application/json:
              schema:
                title: Default success template
                type: object
                additionalProperties:
                  type: object
                description:
                  This method either only returns a brief _OK_ response
                  or a verbose schema is not available for this method.
        default:
          description: Typical error response
          content:
            application/json:
              schema:
                title: Default error template
                type: object
                additionalProperties:
                  type: object
                description:
                  This method either only returns a brief _not OK_ response
                  or a verbose schema is not available for this method.
      security:
        - V1Oauth2:
            - admin.teams:write
