paths:
  /admin.teams.settings.setName:
    post:
      tags:
        - admin.teams.settings
        - admin
      description: Set the name of a given workspace.
      externalDocs:
        description: API method documentation
        url: https://api.slack.com/methods/admin.teams.settings.setName
      operationId: admin_teams_settings_setName
      parameters:
        - name: token
          in: header
          description: "Authentication token. Requires scope: `admin.teams:write`"
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - name
                - team_id
              properties:
                team_id:
                  type: string
                  description: ID for the workspace to set the name for.
                name:
                  type: string
                  description: The new name of the workspace.
          application/json:
            schema:
              required:
                - name
                - team_id
              properties:
                team_id:
                  type: string
                  description: ID for the workspace to set the name for.
                name:
                  type: string
                  description: The new name of the workspace.
        required: true
      responses:
        "200":
          description: Typical success response
          content:
            application/json:
              schema:
                title: Default success template
                type: object
                additionalProperties:
                  type: object
                description:
                  This method either only returns a brief _OK_ response
                  or a verbose schema is not available for this method.
        default:
          description: Typical error response
          content:
            application/json:
              schema:
                title: Default error template
                type: object
                additionalProperties:
                  type: object
                description:
                  This method either only returns a brief _not OK_ response
                  or a verbose schema is not available for this method.
      security:
        - V1Oauth2:
            - admin.teams:write
