paths:
  /admin.teams.settings.info:
    get:
      tags:
        - admin.teams.settings
        - admin
      description: Fetch information about settings in a workspace
      externalDocs:
        description: API method documentation
        url: https://api.slack.com/methods/admin.teams.settings.info
      operationId: admin_teams_settings_info
      parameters:
        - name: token
          in: header
          description: "Authentication token. Requires scope: `admin.teams:read`"
          required: true
          schema:
            type: string
        - name: team_id
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Typical success response
          content:
            application/json:
              schema:
                title: Default success template
                type: object
                additionalProperties:
                  type: object
                description:
                  This method either only returns a brief _OK_ response
                  or a verbose schema is not available for this method.
        default:
          description: Typical error response
          content:
            application/json:
              schema:
                title: Default error template
                type: object
                additionalProperties:
                  type: object
                description:
                  This method either only returns a brief _not OK_ response
                  or a verbose schema is not available for this method.
      security:
        - V1Oauth2:
            - admin.teams:read
