on:
  push:
    branches:
      - '**'
      - '!main'

name: feature-branch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.17.x
    - uses: actions/checkout@v3
